### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by yohkun** [lcobucci/jwt#206]
Hi, i have unexplained random error : 
`<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 3 passed to Lcobucci\JWT\Signer\Hmac::doVerify() must be an instance of Lcobucci\JWT\Signer\Key, boolean given, called in C:\Users\admin\programmation\application-tr\application-TR-BO\vendor\lcobucci\jwt\src\Signer\BaseSigner.php on line 42 and defined in C:\Users\admin\programmation\application-tr\application-TR-BO\vendor\lcobucci\jwt\src\Signer\Hmac.php:29
Stack trace:
#0 C:\Users\admin\programmation\application-tr\application-TR-BO\vendor\lcobucci\jwt\src\Signer\BaseSigner.php(42): Lcobucci\JWT\Signer\Hmac-&gt;doVerify('\xA0&lt;\x81D\x07\x084R\xF7R\x03r\xBD}L...', 'eyJ0eXAiOiJKV1Q...', false)
#1 C:\Users\admin\programmation\application-tr\application-TR-BO\vendor\lcobucci\jwt\src\Signature.php(47): Lcobucci\JWT\Signer\BaseSigner-&gt;verify('\xA0&lt;\x81D\x07\x084R\xF7R\x03r\xBD}L...', 'eyJ0eXAiOiJKV1Q...', false)
#2 C:\Users\admin\programmation\application-tr\application-TR-BO\vendor\lcobucci\jwt\src\Token.php(201): Lcobucci\JWT\Signature-&gt;verify(Object(Lcobucci\JWT\Signer\Hmac\Sha256), 'e in <b>C:\Users\admin\programmation\application-tr\application-TR-BO\vendor\lcobucci\jwt\src\Signer\Hmac.php</b> on line <b>29</b><br />
`

Do you ave an idea ?

**Comment by lcobucci** [comment]
@yohkun it looks like you're sending `false` to `Token#verify()`, you should check that

**Comment by yohkun** [comment]
For the key or the secret ?
All my verify call look like : $token->verify(new Sha256(), "secret"))
That will work 40 time and the 41 i will get the error

**Comment by lcobucci** [comment]
> That will work 40 time and the 41 i will get the error

**Comment by lcobucci** [comment]
> For the key or the secret ?

The 2nd argument of `Token#verify()` is your verification key.

> That will work 40 time and the 41 i will get the error

Which version do you have installed (of PHP as well)? I've never had any kind of issue with that and never heard anyone having that kind of issue.

I'd recommend you to use like this though:

```php
$token->verify(new Sha256(), new Key('secret')))
```

**Comment by lcobucci** [comment]
@yohkun any news here? I was checking things and the only possibility I see is when you're using file based keys and for some weird reason the file couldn't be read (which is something that should be verified and is not being done in https://github.com/lcobucci/jwt/blob/3.2.2/src/Signer/Key.php#L67 - I'm opening an issue for that).

**Comment by yohkun** [comment]
Yes, i'm arrived to the same conclusion... i can't explain why but some time for one user only the key is not read...
A verification here could be a good idea

**Comment by inshaf** [comment]
hi.. im having the same issue... not sure when this error appears... it randomly happens.

im using PHP 7.0.8 and "tymon/jwt-auth": "1.0.0-rc.2"

Not sure how to solve the issue.. any solutions ?

**Comment by sachith-aogroup** [comment]
Hi

We are experiencing the same issue at random times in our Lumen project. The functionality works fine most of the times but occupationally we see this error in the logs and when it happens the server returns 500 error.

The packages we use are 
tymon/jwt-auth 1.0.0-rc.5
lcobucci/jwt 3.3.1

JWT_SECRET is correctly setup in the env file and we also have setup a jwt config file.

The complete error log is as follows

`Symfony\Component\Debug\Exception\FatalThrowableError: Argument 3 passed to Lcobucci\JWT\Signer\Hmac::doVerify() must be an instance of Lcobucci\JWT\Signer\Key, null given, called in C:\xampp\htdocs\fv_api\vendor\lcobucci\jwt\src\Signer\BaseSigner.php on line 44 in C:\xampp\htdocs\fv_api\vendor\lcobucci\jwt\src\Signer\Hmac.php:29
Stack trace:
#0 C:\xampp\htdocs\api\vendor\lcobucci\jwt\src\Signer\BaseSigner.php(44): Lcobucci\JWT\Signer\Hmac->doVerify('\x80\x02#\xB7"\xA9/kP\t\x95\xCAM}\xA7...', 'eyJ0eXAiOiJKV1Q...', NULL)
#1 C:\xampp\htdocs\api\vendor\lcobucci\jwt\src\Signature.php(47): Lcobucci\JWT\Signer\BaseSigner->verify('\x80\x02#\xB7"\xA9/kP\t\x95\xCAM}\xA7...', 'eyJ0eXAiOiJKV1Q...', NULL)
#2 C:\xampp\htdocs\api\vendor\lcobucci\jwt\src\Token.php(201): Lcobucci\JWT\Signature->verify(Object(Lcobucci\JWT\Signer\Hmac\Sha256), 'eyJ0eXAiOiJKV1Q...', NULL)
#3 C:\xampp\htdocs\api\vendor\tymon\jwt-auth\src\Providers\JWT\Lcobucci.php(136): Lcobucci\JWT\Token->verify(Object(Lcobucci\JWT\Signer\Hmac\Sha256), NULL)
#4 C:\xampp\htdocs\api\vendor\tymon\jwt-auth\src\Manager.php(101): Tymon\JWTAuth\Providers\JWT\Lcobucci->decode('eyJ0eXAiOiJKV1Q...')
#5 C:\xampp\htdocs\api\vendor\tymon\jwt-auth\src\JWT.php(200): Tymon\JWTAuth\Manager->decode(Object(Tymon\JWTAuth\Token))
#6 C:\xampp\htdocs\api\vendor\illuminate\support\Facades\Facade.php(237): Tymon\JWTAuth\JWT->getPayload(Object(Tymon\JWTAuth\Token))
#7 C:\xampp\htdocs\api\app\Http\Middleware\JWTMiddleware.php(27): Illuminate\Support\Facades\Facade::__callStatic('getPayload', Array)
#8 C:\xampp\htdocs\api\vendor\illuminate\pipeline\Pipeline.php(163): App\Http\Middleware\JWTMiddleware->handle(Object(Laravel\Lumen\Http\Request), Object(Closure))
#9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Laravel\Lumen\Http\Request))
#10 C:\xampp\htdocs\api\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Laravel\Lumen\Http\Request))
#11 C:\xampp\htdocs\api\vendor\illuminate\pipeline\Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Laravel\Lumen\Http\Request))
#12 C:\xampp\htdocs\api\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(415): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 C:\xampp\htdocs\api\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(261): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#14 C:\xampp\htdocs\api\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(165): Laravel\Lumen\Application->handleFoundRoute(Array)
#15 C:\xampp\htdocs\api\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(418): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Laravel\Lumen\Http\Request))
#16 C:\xampp\htdocs\api\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(171): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#17 C:\xampp\htdocs\api\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(108): Laravel\Lumen\Application->dispatch(NULL)
#18 C:\xampp\htdocs\api\index.php(28): Laravel\Lumen\Application->run()
#19 {main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 3 passed to Lcobucci\\JWT\\Signer\\Hmac::doVerify() must be an instance of Lcobucci\\JWT\\Signer\\Key, null given, called in C:\\xampp\\htdocs\\api\\vendor\\lcobucci\\jwt\\src\\Signer\\BaseSigner.php on line 44 at C:\\xampp\\htdocs\\api\\vendor\\lcobucci\\jwt\\src\\Signer\\Hmac.php:29)
[stacktrace]
#0 C:\\xampp\\htdocs\\api\\vendor\\lcobucci\\jwt\\src\\Signer\\BaseSigner.php(44): Lcobucci\\JWT\\Signer\\Hmac->doVerify('\\x80\\x02#\\xB7\"\\xA9/kP\\t\\x95\\xCAM}\\xA7...', 'eyJ0eXAiOiJKV1Q...', NULL)
#1 C:\\xampp\\htdocs\\api\\vendor\\lcobucci\\jwt\\src\\Signature.php(47): Lcobucci\\JWT\\Signer\\BaseSigner->verify('\\x80\\x02#\\xB7\"\\xA9/kP\\t\\x95\\xCAM}\\xA7...', 'eyJ0eXAiOiJKV1Q...', NULL)
#2 C:\\xampp\\htdocs\\api\\vendor\\lcobucci\\jwt\\src\\Token.php(201): Lcobucci\\JWT\\Signature->verify(Object(Lcobucci\\JWT\\Signer\\Hmac\\Sha256), 'eyJ0eXAiOiJKV1Q...', NULL)
#3 C:\\xampp\\htdocs\\api\\vendor\\tymon\\jwt-auth\\src\\Providers\\JWT\\Lcobucci.php(136): Lcobucci\\JWT\\Token->verify(Object(Lcobucci\\JWT\\Signer\\Hmac\\Sha256), NULL)
#4 C:\\xampp\\htdocs\\api\\vendor\\tymon\\jwt-auth\\src\\Manager.php(101): Tymon\\JWTAuth\\Providers\\JWT\\Lcobucci->decode('eyJ0eXAiOiJKV1Q...')
#5 C:\\xampp\\htdocs\\api\\vendor\\tymon\\jwt-auth\\src\\JWT.php(200): Tymon\\JWTAuth\\Manager->decode(Object(Tymon\\JWTAuth\\Token))
#6 C:\\xampp\\htdocs\\api\\vendor\\illuminate\\support\\Facades\\Facade.php(237): Tymon\\JWTAuth\\JWT->getPayload(Object(Tymon\\JWTAuth\\Token))
#7 C:\\xampp\\htdocs\\api\\app\\Http\\Middleware\\JWTMiddleware.php(27): Illuminate\\Support\\Facades\\Facade::__callStatic('getPayload', Array)
#8 C:\\xampp\\htdocs\\api\\vendor\\illuminate\\pipeline\\Pipeline.php(163): App\\Http\\Middleware\\JWTMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))
#9 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#10 C:\\xampp\\htdocs\\api\\vendor\\laravel\\lumen-framework\\src\\Routing\\Pipeline.php(32): call_user_func(Object(Closure), Object(Laravel\\Lumen\\Http\\Request))
#11 C:\\xampp\\htdocs\\api\\vendor\\illuminate\\pipeline\\Pipeline.php(104): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#12 C:\\xampp\\htdocs\\api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(415): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#13 C:\\xampp\\htdocs\\api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(261): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#14 C:\\xampp\\htdocs\\api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(165): Laravel\\Lumen\\Application->handleFoundRoute(Array)
#15 C:\\xampp\\htdocs\\api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(418): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#16 C:\\xampp\\htdocs\\api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(171): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#17 C:\\xampp\\htdocs\\api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(108): Laravel\\Lumen\\Application->dispatch(NULL)
#18 C:\\xampp\\htdocs\\api\\index.php(28): Laravel\\Lumen\\Application->run()
#19 {main}
"} `

Please advise.

Thanks

**Comment by Ocramius** [comment]
@sachith-aogroup please write a reproduction test case, then report in a new issue after you have a runnable example.

**Comment by sachith-aogroup** [comment]
@Ocramius This is a random issue so not sure how I can reproduce it when it doesn't happen all the time.

**Comment by Ocramius** [comment]
That's why a test scenario is needed: only you have access to the environment where this is happening.

**Comment by sachith-aogroup** [comment]
We are trying to figure out when or how this happens too. All we can see is the error message (which I copied in Lumen logs) time to time. I understand its difficult to debug without a proper test scenario but at the same time its difficult to reproduce a test case when the error doesn't happen all the time. As the library developer , I though you guys would have better insight on this exception so we can investigate it more. Does this error mean the library is unable to read the JWT security key defined in the env file? We use a config file but that uses the value from Thanks

**Comment by lcobucci** [comment]
@sachith-aogroup you have several layers between your application and this lib, which makes things quite complicated.

As you can see on the stack trace, the library [`tymon/jwt-auth`](https://github.com/tymondesigns/jwt-auth) is sending `null` to the verification process, which causes the error:

```
#0 C:\xampp\htdocs\api\vendor\lcobucci\jwt\src\Signer\BaseSigner.php(44): Lcobucci\JWT\Signer\Hmac->doVerify('\x80\x02#\xB7"\xA9/kP\t\x95\xCAM}\xA7...', 'eyJ0eXAiOiJKV1Q...', NULL)
#1 C:\xampp\htdocs\api\vendor\lcobucci\jwt\src\Signature.php(47): Lcobucci\JWT\Signer\BaseSigner->verify('\x80\x02#\xB7"\xA9/kP\t\x95\xCAM}\xA7...', 'eyJ0eXAiOiJKV1Q...', NULL)
#2 C:\xampp\htdocs\api\vendor\lcobucci\jwt\src\Token.php(201): Lcobucci\JWT\Signature->verify(Object(Lcobucci\JWT\Signer\Hmac\Sha256), 'eyJ0eXAiOiJKV1Q...', NULL)
#3 C:\xampp\htdocs\api\vendor\tymon\jwt-auth\src\Providers\JWT\Lcobucci.php(136): Lcobucci\JWT\Token->verify(Object(Lcobucci\JWT\Signer\Hmac\Sha256), NULL)
```

That lib simply doesn't have any type safety, which allowed `null` to be [passed to it as constructor argument](https://github.com/tymondesigns/jwt-auth/blob/1.0.0/src/Providers/JWT/Lcobucci.php#L65) and then be [sent to `lcobucci/jwt`](https://github.com/tymondesigns/jwt-auth/blob/1.0.0/src/Providers/JWT/Lcobucci.php#L136).

If you're using an environment variable for the secret (either via a `.env` file or by setting the variable on your deployment), it sounds like the variable couldn't be found (by `env()`, since you're using Laravel) and then it's falling back to the default value, `null`.

All the evidence tells me that `lcobucci/jwt` isn't the problematic one on this matter :smile:
