### ISSUE TITLE
Fatal error: Uncaught InvalidArgumentException: It was not possible to parse your key, reason: error:0906D06C:PEM routines:PEM_read_bio:no 

### ISSUE THREAD

**Issue by flik** [lcobucci/jwt#240]
**code**:
```php
use Lcobucci\JWT\Builder;
use Lcobucci\JWT\Signer\Keychain; // just to make our life simpler
use Lcobucci\JWT\Signer\Rsa\Sha256; // you can use Lcobucci\JWT\Signer\Ecdsa\Sha256 if you're using ECDSA keys

$signer = new Sha256();

$keychain = new Keychain();

$token = (new Builder())->setIssuer('https://services.poynt.net') // Configures the issuer (iss claim)
                        ->setAudience('https://services.poynt.net') // Configures the audience (aud claim)
                        ->setId('4f1g23a12aa', true) // Configures the id (jti claim), replicating as a header item
                        ->setIssuedAt(time()) // Configures the time that the token was issue (iat claim)
                        ->setNotBefore(time() + 60) // Configures the time that the token can be used (nbf claim)
                        ->setExpiration(time() + 3600) // Configures the expiration time of the token (nbf claim)
                        ->set('uid', 1) // Configures a new claim, called "uid"
                        ->sign($signer,  $keychain->getPrivateKey('private.ppk')) // creates a signature using your private key
                        ->getToken(); // Retrieves the generated token

var_dump($token->verify($signer, $keychain->getPublicKey('public.pub'))); // true when the public key was generated by the private one =)  
```
**error**:

Fatal error: Uncaught InvalidArgumentException: It was not possible to parse your key, reason: error:0906D06C:PEM routines:PEM_read_bio:no start line in C:\xampp\htdocs\getToken\vendor\lcobucci\jwt\src\Signer\Rsa.php:60 Stack trace: #0 C:\xampp\htdocs\getToken\vendor\lcobucci\jwt\src\Signer\Rsa.php(26): Lcobucci\JWT\Signer\Rsa->validateKey(false) #1 C:\xampp\htdocs\getToken\vendor\lcobucci\jwt\src\Signer\BaseSigner.php(34): Lcobucci\JWT\Signer\Rsa->createHash('eyJ0eXAiOiJKV1Q...', false) #2 C:\xampp\htdocs\getToken\vendor\lcobucci\jwt\src\Builder.php(241): Lcobucci\JWT\Signer\BaseSigner->sign('eyJ0eXAiOiJKV1Q...', Object(Lcobucci\JWT\Signer\Key)) #3 C:\xampp\htdocs\getToken\index.php(20): Lcobucci\JWT\Builder->sign(Object(Lcobucci\JWT\Signer\Rsa\Sha256), Object(Lcobucci\JWT\Signer\Key)) #4 {main} thrown in C:\xampp\htdocs\getToken\vendor\lcobucci\jwt\src\Signer\Rsa.php on line 60

**Comment by lcobucci** [comment]
@flik I assume that you're using a file called `public.pub` for your public key, if you don't add the `file://` prefix the lib won't know of that and will use the string `public.pub` as key (which is an invalid RSA key). The examples in https://github.com/lcobucci/jwt/tree/3.2#rsa-and-ecdsa show that.

I agree that this is not really explicit and we're already changing stuff for v4 (which will probably be ported back to v3.x).

**Comment by lcobucci** [comment]
Please let me know if that solves your problem so that we can close this issue 👍.

**Comment by flik** [comment]
things fixed. thanks. :)

**Comment by PenguinTamer** [comment]
Hi there, Im currently experiencing the same error/issue. I've specified my path correctly, i think i did at least. Are there any other reasons this error could be thrown? It's a freshly generated token too.

```
namespace App\Http\Middleware;

use Closure;
use Lcobucci\JWT\ValidationData;
use Lcobucci\JWT\Signer\Key;
use Lcobucci\JWT\Signer\Rsa\Sha256;
use Lcobucci\JWT\Parser;
use Lcobucci\JWT\Token as ParsedToken;

class tokenValidator
{

    /**
     * @var Key $publickKey
     */
    private $publicKey;
    /**
     * @var Parser $parser
     */
    private $parser;
    /**
     * @var Signer $signer
     */
    private $signer;

    /**
     * Constructor
     *
     * Assigns public key for token verification - Change as needed
     * Assigns algorithm used to sign token - Change as needed
     * Creates a Parser to parse JWT tokens
     */
    public function __construct() {
        $this->publicKey = new Key('file:://storage/oauth-public.key');
        $this->parser = new Parser();
        $this->signer = new Sha256();
    }

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (!$request['access_token']) {
            return response()->json(['message' =>'Access token is missing. Get it together morty'], 401);
        }

        $token = $request['access_token'];
        $parsedToken = $this->getParsedToken($token);
        dd($parsedToken->verify($this->signer, $this->publicKey));

        return $next($request);
    }
    /**
     *
     */
    private function verifyToken(ParsedToken $parsedToken) {
        return $parsedToken->verify($this->signer, $this->publicKey);
    }
```
