### ISSUE TITLE
Claims iat, nbf, exp do not correspond  RFC 7519  

### ISSUE THREAD

**Issue by VitaliyDior** [lcobucci/jwt#604]
In case of non zero Firebase\JWT::$jeeway MicrosecondBasedDateConversion converts iat, nbf, exp claims into strings. 
According to RFC 7519  they 

> MUST be a number containing a NumericDate value

This issue has high impact on strict typed languages, for example  java-jwt throws the following error
```
2020-12-09T16:20:11.770+01:00	com.auth0.jwt.exceptions.JWTDecodeException: The claim 'exp' contained a non-numeric date value.
2020-12-09T16:20:11.770+01:00	at com.auth0.jwt.impl.PayloadDeserializer.getDateFromSeconds(PayloadDeserializer.java:75)
2020-12-09T16:20:11.772+01:00	at com.auth0.jwt.impl.PayloadDeserializer.deserialize(PayloadDeserializer.java:41)
2020-12-09T16:20:11.772+01:00	at com.auth0.jwt.impl.PayloadDeserializer.deserialize(PayloadDeserializer.java:16)
2020-12-09T16:20:11.772+01:00	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
2020-12-09T16:20:11.772+01:00	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1219)
2020-12-09T16:20:11.772+01:00	at com.auth0.jwt.impl.JWTParser.parsePayload(JWTParser.java:36)
2020-12-09T16:20:11.772+01:00	at com.auth0.jwt.JWTDecoder.<init>(JWTDecoder.java:44)
2020-12-09T16:20:11.772+01:00	at com.auth0.jwt.JWTDecoder.<init>(JWTDecoder.java:30)
2020-12-09T16:20:11.773+01:00	at com.auth0.jwt.JWT.decode(JWT.java:45)
```

**Comment by lcobucci** [comment]
@VitaliyDior if you search for NumericDate on the RFC you'll find:

> NumericDate
> A JSON numeric value representing the number of seconds from 1970-01-01T00:00:00Z UTC until the specified UTC date/time, ignoring leap seconds. This is equivalent to the IEEE Std 1003.1, 2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in which each day is accounted for by exactly 86400 seconds, other than that non-integer values can be represented. See RFC 3339 [RFC3339] for details regarding date/times in general and UTC in particular.

To prevent issues with floating point precision, we use strings to represent microseconds.

On our docs we provide examples on how to use claim formatters to always use integers for these date objects: https://lcobucci-jwt.readthedocs.io/en/latest/extending-the-library/#claims-formatter

**Comment by VitaliyDior** [comment]
Ok, but If I understand correctly, docs said that default claims formatter returns float

> format date based claims using microseconds (float)

**Comment by lcobucci** [comment]
> Ok, but If I understand correctly, docs said that default claims formatter returns float
> 
> > format date based claims using microseconds (float)

That's a documentation issue, thanks for pointing it out.

**Comment by mtangoo** [comment]
Just faced same issue and bumped this thread. Adding this as a topic to documentation will be great. The current linked documentation example is not commented which requires one inspect involved classes to understand them.
Thank you for such a nice library!
