### ISSUE TITLE
 Error while decoding from JSON in lcobucci/jwt/src/Encoding/CannotDecodeContent.php

### ISSUE THREAD

**Issue by amrishkakadiya** [lcobucci/jwt#729]
Hello, I have perfect working code in Local and Dedicated nginx server.

Now I am copied that code into Apache Shared Hosting, And while parsing tokens, I am getting below error.

```
Next Lcobucci\JWT\Encoding\CannotDecodeContent: Error while decoding from JSON in /home/puomhfih/public_html/rms/vendor/lcobucci/jwt/src/Encoding/CannotDecodeContent.php:14
Stack trace:
#0 /home/puomhfih/public_html/rms/vendor/lcobucci/jwt/src/Encoding/JoseEncoder.php(41): Lcobucci\JWT\Encoding\CannotDecodeContent::jsonIssues(Object(JsonException))
#1 /home/puomhfih/public_html/rms/vendor/lcobucci/jwt/src/Token/Parser.php(67): Lcobucci\JWT\Encoding\JoseEncoder->jsonDecode('ZXlKMGVYQWlPaUp...')
#2 /home/puomhfih/public_html/rms/vendor/lcobucci/jwt/src/Token/Parser.php(30): Lcobucci\JWT\Token\Parser->parseHeader('eyJ0eXAiOiJKV1Q...')
#3 /home/puomhfih/public_html/rms/app/Http/Middleware/ParseToken.php(38): Lcobucci\JWT\Token\Parser->parse('eyJ0eXAiOiJKV1Q...')
#4 /home/puomhfih/public_html/rms/vendor/illuminate/pipeline/Pipeline.php(167): App\Http\Middleware\ParseToken->handle(Object(Laravel\Lumen\Http\Request), Object(Closure))
#5 /home/puomhfih/public_html/rms/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Laravel\Lumen\Http\Request))
#6 /home/puomhfih/public_html/rms/app/Http/Middleware/CorsMiddleware.php(60): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Laravel\Lumen\Http\Request))
#7 /home/puomhfih/public_html/rms/vendor/illuminate/pipeline/Pipeline.php(167): App\Http\Middleware\CorsMiddleware->handle(Object(Laravel\Lumen\Http\Request), Object(Closure))
#8 /home/puomhfih/public_html/rms/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Laravel\Lumen\Http\Request))
#9 /home/puomhfih/public_html/rms/vendor/illuminate/pipeline/Pipeline.php(103): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Laravel\Lumen\Http\Request))
#10 /home/puomhfih/public_html/rms/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(423): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#11 /home/puomhfih/public_html/rms/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(172): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#12 /home/puomhfih/public_html/rms/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(109): Laravel\Lumen\Application->dispatch(NULL)
#13 /home/puomhfih/public_html/rms/public/index.php(28): Laravel\Lumen\Application->run()
#14 {main}  

```
And Here is my code to parse

```
$aConfig = Auth::getConfig(env('X_TOKEN_KEY'));
  $aToken =  $aConfig->parser()->parse(Crypt::decrypt($req->header('x-token')));
```

And as Per [documentation ](https://lcobucci-jwt.readthedocs.io/en/stable/parsing-tokens/) I am pasing raw string token received in header and I am not passing that raw string to **Decoding Function**, that is done by **parser()** which is perfectly working in local ane other server.

Can anyone help?

**Comment by lcobucci** [comment]
Let's continue with the previous issue instead of opening a new one please.
