### ISSUE TITLE
base642binFallback returns boolean instead of string

### ISSUE THREAD

**Issue by talismandev** [lcobucci/jwt#760]
Hello.
My name is Nickolai, I am using this jwt library in Laravel Passport Package. 

Laravel version: 8.12
PHP Version: 7.4.19

I encountered strange behavior (actually, passport api routes always returned 'unauthenticated'). 
After some debugging, I found this in laravel logs: 

```
[object] (Lcobucci\\JWT\\Encoding\\CannotDecodeContent(code: 0): Error while decoding from Base64Url, invalid base64 characters detected at /[path_to_my_project]/lcobucci/jwt/src/Encoding/CannotDecodeContent.php:19)
[stacktrace]
#0 /[path_to_my_project]/lcobucci/jwt/src/SodiumBase64Polyfill.php(83): Lcobucci\\JWT\\Encoding\\CannotDecodeContent::invalidBase64String()
#1 /[path_to_my_project]/lcobucci/jwt/src/SodiumBase64Polyfill.php(60): Lcobucci\\JWT\\SodiumBase64Polyfill::base642binFallback('YSqXMwU8rLmKg70...', 7)
#2 /[path_to_my_project]/lcobucci/jwt/src/Encoding/JoseEncoder.php(57): Lcobucci\\JWT\\SodiumBase64Polyfill::base642bin('YSqXMwU8rLmKg70...', 7)
#3 /[path_to_my_project]/lcobucci/jwt/src/Token/Parser.php(150): Lcobucci\\JWT\\Encoding\\JoseEncoder->base64UrlDecode('YSqXMwU8rLmKg70...')
#4 /[path_to_my_project]/lcobucci/jwt/src/Token/Parser.php(38): Lcobucci\\JWT\\Token\\Parser->parseSignature(Array, 'YSqXMwU8rLmKg70...')
#5 /[path_to_my_project]/league/oauth2-server/src/AuthorizationValidators/BearerTokenValidator.php(99): Lcobucci\\JWT\\Token\\Parser->parse('eyJ0eXAiOiJKV1Q...')
#6 /[path_to_my_project]/league/oauth2-server/src/ResourceServer.php(84): League\\OAuth2\\Server\\AuthorizationValidators\\BearerTokenValidator->validateAuthorization(Object(Nyholm\\Psr7\\ServerRequest))
#7 /[path_to_my_project]/laravel/passport/src/Guards/TokenGuard.php(204): League\\OAuth2\\Server\\ResourceServer->validateAuthenticatedRequest(Object(Nyholm\\Psr7\\ServerRequest))
#8 /[path_to_my_project]/laravel/passport/src/Guards/TokenGuard.php(147): Laravel\\Passport\\Guards\\TokenGuard->getPsrRequestViaBearerToken(Object(Illuminate\\Http\\Request))
#9
...
```

And found, that in SodiumBase64Polyfill class, base642binFallback fn returns boolean, when processing the third part of the token.

I spent several hours trying to figure out why this was happening. 

And I fixed it in this way: 

in public static function base642binFallback(....  find line of code:
$decoded = base64_decode($encoded, true); 

I removed strict mode: $decoded = base64_decode($encoded);

And error disappeared.

Here is my token: 

```
wsMxb9U/sD0pE70eEcC98Gk0dzhF9OgE4rO00IEGYgIkUEIhiWctAJHESYk6W+IuzqdzdMeFVdukqx6hWleq7dM9cH10rBOkYFPyE3INah37eFucnIbHQiHh8uKEwdQsbKrjgi/8O2ildDLEbvm7PTsTR4Cuz2dUL9Wrs3NwzcEHBg1iBQYPmshfctvmpjACSXk4CVe/ZMg0IjPfLaEKSUCnPjVfrnky1I5wGlOtZriAOdh8qT8rlWUzU41qp/ViLsiWaq18GQMrtXkyDIuBA7/WyvQXEkGlI2DO+CkgkIfQmFJb4+pLd4les2OTWSP5jvHZkNyczK0ZInqNDw94amsbmrxeLVZHoaXpRwoCZDpa/xZc4WnTGYQlutjE/gdAo7ClbxnjBTK4Qw0Gj0HdIQKvqouBtBd43B7EhCjSBG+4PIVo9l5iHBUnSOtkquVcIq55LpBUlffStErEpeWgzFWsZ1IyjSzNbDnhRvPtSpQBUj5Xc/zph8EhfbrG76nN6QE8u8Yun9zo+gpV+iGh8WZLdhk32jgEGFnHzLsMr1ZVe+jWHbDN3xQv1Q8wBeKbxZhXk2nZNhjW417P8pXvTCwbg+VEvONW409SElb68MY+W+sOc3AYmwdaf8cO0GIpDH5lEUUjudKihiNSvWBWbhp9jRzoLpCmXoRLadUv70A!
```

The question is: why that behavior happened ?

Thank you.

**Comment by Slamdunk** [comment]
Hi, I see that the last char of the pasted base64 is an exclamation mark `!`, which for sure isn't a `base64` character in any known variant, see https://en.wikipedia.org/wiki/Base64

If you remove it, the decoding works fine.

**Comment by talismandev** [comment]
Yeah, definately! Thanks for the quick answer.

Strange, that tokens generated automatically, by laravel passport. 

And everything worked on localhost.

But in another VDS environment, "!" appears.
