### ISSUE TITLE
Error while making an /oauth/token request to laravel 7 application

### ISSUE THREAD

**Issue by manjunathpadolkar** [lcobucci/jwt#776]
Getting below error in laravel 7 project on php 7.4 

```<!--
InvalidArgumentException: It was not possible to parse your key, reason:  in file /home/vagrant/code/me.api.tech/vendor/lcobucci/jwt/src/Signer/OpenSSL.php on line 90

#0 /home/vagrant/code/me.api.tech/vendor/lcobucci/jwt/src/Signer/OpenSSL.php(47): Lcobucci\JWT\Signer\OpenSSL-&gt;validateKey()
#1 /home/vagrant/code/me.api.tech/vendor/lcobucci/jwt/src/Signer/OpenSSL.php(21): Lcobucci\JWT\Signer\OpenSSL-&gt;getPrivateKey()
#2 /home/vagrant/code/me.api.tech/vendor/lcobucci/jwt/src/Signer/BaseSigner.php(36): Lcobucci\JWT\Signer\OpenSSL-&gt;createHash()
#3 /home/vagrant/code/me.api.tech/vendor/lcobucci/jwt/src/Builder.php(470): Lcobucci\JWT\Signer\BaseSigner-&gt;sign()
#4 /home/vagrant/code/me.api.tech/vendor/lcobucci/jwt/src/Builder.php(450): Lcobucci\JWT\Builder-&gt;createSignature()
#5 /home/vagrant/code/me.api.tech/vendor/league/oauth2-server/src/Entities/Traits/AccessTokenTrait.php(53): Lcobucci\JWT\Builder-&gt;getToken()
#6 /home/vagrant/code/me.api.tech/vendor/league/oauth2-server/src/Entities/Traits/AccessTokenTrait.php(61): Laravel\Passport\Bridge\AccessToken-&gt;convertToJWT()
#7 /home/vagrant/code/me.api.tech/vendor/league/oauth2-server/src/ResponseTypes/BearerTokenResponse.php(31): Laravel\Passport\Bridge\AccessToken-&gt;__toString()
#8 /home/vagrant/code/me.api.tech/vendor/league/oauth2-server/src/AuthorizationServer.php(202): League\OAuth2\Server\ResponseTypes\BearerTokenResponse-&gt;generateHttpResponse()
#9 /home/vagrant/code/me.api.tech/vendor/laravel/passport/src/Http/Controllers/AccessTokenController.php(63): League\OAuth2\Server\AuthorizationServer-&gt;respondToAccessTokenRequest()
#10 /home/vagrant/code/me.api.tech/vendor/laravel/passport/src/Http/Controllers/HandlesOAuthErrors.php(24): Laravel\Passport\Http\Controllers\AccessTokenController-&gt;Laravel\Passport\Http\Controllers\{closure}()
#11 /home/vagrant/code/me.api.tech/vendor/laravel/passport/src/Http/Controllers/AccessTokenController.php(65): Laravel\Passport\Http\Controllers\AccessTokenController-&gt;withErrorHandling()
#12 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Laravel\Passport\Http\Controllers\AccessTokenController-&gt;issueToken()
#13 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\Routing\ControllerDispatcher-&gt;dispatch()
#14 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\Routing\Route-&gt;runController()
#15 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\Routing\Route-&gt;run()
#16 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}()
#17 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#18 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handle()
.tech/app/Http/Middleware/PageAnalytics.php(32): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#20 /home/vagrant/code/me.api..tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\PageAnalytics-&gt;handle()
#21 /home/vagrant/code/me.api.tech/app/Http/Middleware/ConvertedUser.php(32): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#22 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\ConvertedUser-&gt;handle()
#23 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#24 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline-&gt;then()
#25 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router-&gt;runRouteWithinStack()
#26 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router-&gt;runRoute()
#27 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router-&gt;dispatchToRoute()
#28 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router-&gt;dispatch()
#29 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}()
#30 /home/vagrant/code/me.api.tech/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#31 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors-&gt;handle()
#32 /home/vagrant/code/me.api.tech/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#33 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies-&gt;handle()
#34 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#35 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle()
#36 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#37 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle()
#38 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#39 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle()
#40 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#41 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle()
#42 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#43 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline-&gt;then()
#44 /home/vagrant/code/me.api.tech/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter()
#45 /home/vagrant/code/me.api.tech/public/index.php(55): Illuminate\Foundation\Http\Kernel-&gt;handle()
#46 {main}

**Comment by lcobucci** [comment]
@manjunathpadolkar it seems like you don't have a valid key configured...

Have you checked that?

**Comment by Ocramius** [comment]
Also check: https://github.com/lcobucci/jwt/blob/a8acedb920bb48de30bad1aa9e6d242903ecd693/src/Signer/OpenSSL.php#L99-L104

At this point of the execution, your `$key` is `false`
